config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :characters, only: %i[new create index show] do
    resources :bookings, only: %i[create]
  end

  resources :bookings, only: %i[destroy edit update] do
    resources :reviews, only: %i[create]
  end
  devise_for :users
  root to: "pages#home"

  get 'dashboard', to: 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :character
  has_one :review, dependent: :destroy

  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :category, presence: true, inclusion: { in: %w[Villains Disney Pixar Marvel DC Action Books Family] }
  validates :character_name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :character, through: :booking

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_one :character

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_nr, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_nr, :address])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_user, only: %i[new create]
  before_action :set_character, only: %i[new create]
  before_action :set_booking, only: %i[destroy edit update]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.character = @character
    @booking.user = @user
    if @booking.save
      flash.alert = 'Your Imaginanny has been reserved!'
      redirect_to character_path(@character)
    else
      render 'characters/show', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to :dashboard, notice: 'Booking was successfully updated.'
    else
      render :dashboard, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def set_user
    @user = current_user
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_character
    @character = Character.find(params[:character_id])
  end

  def booking_params
    params.require(:booking).permit(:date, :character_id, :user_id, :start_time, :end_time)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_user, only: %i[new create]

  def index
    @characters = Character.all
    filter_characters

    if params[:query].present?
      @characters = @characters.where("character_name ILIKE ?", "%#{params[:query]}%")
    end
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    @character.user = @user
    if @character.save
      redirect_to character_path(@character)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @character = Character.find(params[:id])
    @booking = Booking.new
    @reviews = Review.all
  end

  private

  def set_user
    @user = current_user
  end

  def character_params
    params.require(:character).permit(:category, :description, :character_name, :price, :user_id, :photo)
  end

  def filter_characters
    if params[:filter].present?
      @characters = @characters.where(category: params[:filter][:category]) if params[:filter][:category].present?
      @characters = @characters.where("price <= ?", params[:filter][:max_price]) if params[:filter][:max_price].present?
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_user, only: %i[index show edit update]
  # before_action :set_character, only: %i[index show edit update]
  # before_action :set_booking, only: %i[index show edit update]

  def index

    # @user = User.find(current_user.id)
    # @bookings = Booking.where(character: current_user)

    @user = User.find(current_user.id)
    @character = @user.character
    @bookings = Booking.where(character: @character)
    @my_bookings = Booking.where(user: current_user)

    # The `geocoded` scope filters only babysitter with coordinates

    @markers = @bookings.map do |booking|
      {
        lat: booking.user.latitude,
        lng: booking.user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {user: booking.character}),
        marker_html: render_to_string(partial: "marker", locals: {user: booking.character})
      }
    end
  end


  def profile
    @user = User.find(current_user.id)
  end

  def show
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.new
    @user = User.find(current_user.id)
    @user.update(user_params)
  end

  private

  def set_user
    @user = current_user
  end

  # def set_booking
  #   @booking = Booking.find(params[:booking_id])
  # end

  # def set_character
  #   @character = Character.find(params[:character_id])
  # end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :email, :phone_nr, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @random_characters = []
    9.times do
      character = Character.all.sample
      @random_characters << {
        character_name: character.character_name,
        description: character.description,
        category: character.category,
        price: character.price,
        photo: character.photo.url
      }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: %i[new create]
  # before_action :set_character, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to character_path(@booking.character)
      flash.alert = 'Thank you for your review'
    else
      render :dashboard, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_character
    @character = Character.find(params[:character_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :booking_id, :character_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/bookings/_form.html.erb
<div class="card-form">
  <h3>Book an Imaginanny</h3>

  <%= simple_form_for [@character, @booking], html: { class: 'booking-form' } do |f| %>
    <div class="form-group">
      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.input :start_time, class: 'form-control', as: :time, :minute_step => 15 %>
    </div>

  <div class="form-group">
    <%= f.input :end_time, class: 'form-control', as: :time, :minute_step => 15 %>
  </div>

    <div class="form-group">
      <%= f.submit "Book", class: "btn" %>
    </div>
  <% end %>

</div>

app/views/bookings/edit.html.erb
<div class="container">
<h1>Edit your booking</h1>
<p>You can change the date and time</p>
<%= render "form", booking: @booking %>
</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>
<%= render "bookings/form", booking: @booking %>

app/views/characters/_form.html.erb
<%= simple_form_for(@character) do |f| %>
  <%= f.input :category, collection: %w[Villains Disney Pixar Marvel DC Action Books Family] %>
  <%= f.input :character_name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create Character", class:"btn" %>
<% end %>

app/views/characters/index.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Looking for an imaginnany!</title>
</head>

<body>
  <div class="container">
    <h1 class="mt-5">All Imaginannys</h1>
    <p>Filter your search</p>
    <%= simple_form_for :filter, url: characters_path, method: :get do |f| %>
      <%= f.input :category, collection: %w[Villains Disney Pixar Marvel DC Action Books Family] %>
      <%= f.input :max_price, input_html: {placeholder: "Max price"} %>
      <%= f.submit "Filter", class:"btn" %>
    <% end %>

    <%# Displaying the characters %>
    </div>

    <div class = "container">
      <div class ="text">
      <% if @characters.any? %>
        <div class="row">
      <div class="cardContainer">
      <% @characters.each do |character| %>
        <%= link_to character_path(character), class: "card-links" do %>
          <div class="card col-lg-4">
            <div class="card-image"
                style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2))">
            <%= image_tag character.photo, height: 250, gravity: :face %>
            </div> <!-- fin card-image -->
              <div class="card-description">
                <p><strong id="name"><td><%= character.character_name %></td></strong></p>
                <p id="category"><%= character.category %></p>
                <p id="description"><%= character.description.split(/[.!]/).first.strip %></p>
                <div id="price">
                  <p><td><%= character.price %>€/h</td></p>
                </div>
              </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
          </div>
      <% else %>
        <h4>No characters found.</h4>
      <% end %>
    </div>
</body>
</html>

app/views/characters/new.html.erb
<h1 class="character_head">Create Character</h1>
<p></p>
<div class="container">
<%= render 'form', character: @character %>
</div>

<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Looking for an imaginnany!</title>
</head>

<body>
  <div class="container">
    <h1 class="mt-5">Add a new sitter!</h1>
    <p>Add a new imaginnany </p>
    <div class="container">
    <%= render 'form', character: @character %>
    </div>
  </div>
  </body>
</html>

app/views/characters/show.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My character</title>
</head>

<body>
  <div class="container">

    <h1 class="mt-5 mb-5"><%= @character.character_name %></h1>
    <div class="show_content">
      <div class="show_img">
        <%= image_tag @character.photo.url, gravity: :face%>
      </div>
      <div class="description">
        <div>
          <p><strong>Description: </strong></p>
          <p><%= @character.description %></p>
        </div>
        <div>
          <p><strong>Category:</strong></p>
          <p><%= @character.category %></p>
        </div>
        <div>
          <p><strong>Price:</strong></p>
          <p><%= @character.price %>€/hour</p>
        </div>
      </div>


    </div>
    <%= render "bookings/form", booking: @booking %>
    <%= render "shared/flashes" %>
    <div>

    <h3 id="review-title">What others people have said about <%= @character.character_name %></h3>

      <% @character.bookings.each do |booking| %>
        <% if booking.review.present? %>
          <p><%= booking.review.content %></p>
          <p><%= '⭐️' * booking.review.rating %></p>
        <% else %>
          <p>There isn't any reviews about <%= @character.character_name %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/dashboards/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/dashboards/_info_window.html.erb
<h2><%= user.character_name %></h2>

app/views/dashboards/_marker.html.erb
<%= image_tag "imaginanny-logo.png", height: 30, width: 30, alt: "Logo" %>

<%# <div class="badge rounded-pill bg-primary fs-6">
  <%= flat.name %>
<%# </div> %>

app/views/dashboards/index.html.erb
  <div class="image_container">
  <div class="profile-image">
    <%=image_tag "mother.jpeg", class:"profile"%>
  </div>

<div class="container">


  <h1>My Profile</h1>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Details</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">My Sittings</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane" aria-selected="false">Booked Imaginannys</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="map-tab" data-bs-toggle="tab" data-bs-target="#map-tab-pane" type="button" role="tab" aria-controls="map-tab-pane" aria-selected="false">Map</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0" data-controller="toggle">
    <div class="user-details" data-toggle-target="detail">
      <p class="mt-3"><strong>First name: </strong><%= current_user.first_name  %></p>
      <p><strong>Last name: </strong><%= current_user.last_name  %></p>
      <p><strong>Address: </strong><%= current_user.address %></p>
      <p><strong>Email: </strong><%= current_user.email  %></p>
      <p><strong>Phone number: </strong><%= current_user.phone_nr  %></p>
      <button class="btn" data-action="click->toggle#fire">Edit</button>
      <% unless @user.character.present?  %>
        <a href="characters/new"><button class="btn">Create Character</button></a>
      <% end %>
    </div>
    <div class="user-change d-none" data-toggle-target="form">
      <%= render 'devise/registrations/edit'  %>
    </div>
    <div class="container_cancel">
      <%= render "devise/registrations/cancel" %>
    </div>
  </div>
  <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
    <div class="tab-bookings">
        <% if @bookings.any? %>
          <% @bookings.each do |booking| %>

              <p class="mt-5"><strong><%= booking.character.character_name %></strong></p>
              <p>Date: <strong><%= booking.date.strftime('%b %e') %></strong></p>

              <p>Start time: <strong><%= booking.start_time.strftime("%H:%M") if booking.start_time.present? %></strong></p>
              <p>End time: <strong><%= booking.end_time.strftime("%H:%M") if booking.end_time.present? %></strong></p>
          <% end %>
        <% else %>
          <p class="booking_txt mt-3">No Bookings</p>
        <% end %>
      </div>
  </div>
  <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">
    <div class="bookings">

          <% if @my_bookings.any? %>
            <% @my_bookings.each do |booking| %>

              <p class="mt-5"><strong><%= booking.character.character_name %></strong></p>
              <p>Date: <strong><%= booking.date.strftime('%b %e') %></strong></p>

              <p>Start time: <strong><%= booking.start_time.strftime("%H:%M") if booking.start_time.present? %></strong></p>
              <p>End time: <strong><%= booking.end_time.strftime("%H:%M") if booking.end_time.present? %></strong></p>
              <% if booking.date.future? %>
                <button class="btn"><%= link_to 'edit', edit_booking_path(booking) %></button>
                <button class="btn"><%= link_to 'cancel', booking_path(booking),  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></button>
              <% end %>

            <div class="add-reviews" data-controller="toggle">
              <% if booking.date.past? %>
                <div data-toggle-target="btnReview">
                  <button class="btn" data-action="click->toggle#review">Leave a review for your imaginanny</button>
                </div>
                <div class="d-none" data-toggle-target="formReview">
                  <%= simple_form_for [booking, Review.new] do |f| %>
                    <%= f.input :content %>
                    <%= f.input :rating %>
                    <%= f.button :submit, "Review your Imaginanny", class: "btn" %>
                    <%= render "shared/flashes" %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <% end %>
          <% else %>
            <p class="booking_txt mt-3">No bookings</p>
          <% end %>

      </div>
  </div>
  <div class="tab-pane fade" id="map-tab-pane" role="tabpanel" aria-labelledby="map-tab" tabindex="0">
    <div>
        <div style="width: 800px; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          <%= render 'marker', dashboard: @dashboard %>
        </div>
      </div>
  </div>
</div>



  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imaginanny</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 <div class="page-container">
  <div class="navbar-container"><%= render "shared/navbar" %></div>
  <div class="content-container"><%= yield %></div>
  <div class="footer-sticky-container"><%= render "shared/footer" %></div>
</div>
  </body>
</html>

app/views/pages/_search.html.erb
<%= form_with url: characters_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Character Name..."
    %>
  <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
<% end %>

app/views/pages/home.html.erb
<html>
<head>
  <title>Imaginanny</title>
  <!-- Include your CSS and other header content here -->
</head>
<body>

<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner banners">
    <div class="carousel-item active">
      <%= image_tag("banner1.png") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("banner2.png") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("banner3.png") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("banner4.png") %>
    </div>
  </div>
</div>




<div class = "container">
<div class ="text">
<p>Featured</p>
</div>
  <div class="row">
      <div class="cardContainer">
      <% @random_characters.each do |character| %>
        <%= link_to characters_path(character), class: "card-links" do %>
          <div class="card col-lg-4">
            <div class="card-image"
                style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2))">
            <%= image_tag character[:photo], height: 250, gravity: :face %>
            </div> <!-- fin card-image -->
              <div class="card-description">
                <p><strong id="name"><td><%= character[:character_name]%></td></strong></p>
                <p id="category"><%= character[:category] %></p>
                <p><%= character[:description].split(/[.!]/).first.strip %></p>
                <div id="price">
                  <p><td><%= character[:price]%>€/h</td></p>
                </div>
              </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<!-- Your main content for the home page goes here -->
</body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-container">
    <div>
      <div class="text">
        <ul class="footer-nav">
          <li>&copy; <%= Time.now.year %> Imaginanny</li>
          <li> • </li>
          <li><a href="#" class="link">About Us</a></li>
          <li> • </li>
          <li><a href="#" class="link">Terms of Service</a></li>
          <li> • </li>
          <li><a href="#" class="link">Privacy Policy</a></li>
          <li> • </li>
          <li><a href="https://facebook.com/example"><i class="fab fa-facebook"></i></a></li>
          <li><a href="https://twitter.com/example"><i class="fab fa-twitter"></i></a></li> <!-- Add more navigation links as needed -->
        </ul>
        <%# <a href="mailto:info@imaginanny.com">info@imaginanny.com</a> or call us at +1234567890. %>
        <%# <ul class="social-media-links">
          <li><a href="https://facebook.com/example"><i class="fab fa-facebook"></i></a></li>
          <li><a href="https://twitter.com/example"><i class="fab fa-twitter"></i></a></li> <!-- Add more social media links as needed -->
        </ul> %>
      </div>
      <%# <div class="col-md-6">
        <ul class="footer-nav">
          <li><a href="#">About Us</a></li>
          <li><a href="#">Terms of Service</a></li>
          <li><a href="#">Privacy Policy</a></li> <!-- Add more navigation links as needed -->
        </ul> %>
        <%# <form class="subscribe-form" action="/subscribe" method="post">
          <input type="email" name="email" placeholder="Your email address">
          <button type="submit">Subscribe</button>
        </form> %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="nav-bar">
    <div class="home-navbar">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "imaginanny-logo.png", class: "logo" %>
    <% end %>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "My Profile", :dashboard, id: "nav-profile" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="search-bar-container">
        <ul class="navbar-nav">
          <li class="nav-item flex-grow-1">
              <div class="search-bar p-2 flex-lg-row">
                <%= form_with url: characters_path, method: :get, class: "d-flex" do %>
                  <%= text_field_tag :query,
                        params[:query],
                        class: "form-control",
                        placeholder: "Character Name..."
                    %>
                  <%= submit_tag "Search", name: "", class: "btn btn-primary", id: "search-btn" %>
                <% end %>
              </div>
            </li>
        </ul>
      </div>
  </div>
</div>